apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: charts
    contents:
      - path: cert-manager
        helmChart:
          name: cert-manager
          version: v1.19.1
          repository:
            url: https://charts.jetstack.io
